### PR TITLE
Change event listeners

### LINKED ISSUE #11: Listener frequently added but not triggered
I'm a bit hesitant to open an issue that is basically "it doesn't work", but I'm finding that frequently the description copy isn't happening.

I added a bunch of logging to see what's going wrong, and it looks like the listener gets added but doesn't get triggered. https://github.com/GMNGeoffrey/squashed-merge-message/blob/logging/content.js

"Adding listener" shows up in the logs, but none of the other messages do. This is an intermittent issue. If I empty cache and hard reload a few times, it usually works eventually. I'll continue to try and see if I can get a reliable repro. It seems like once I've gotten it to work for a PR it works every time.

### PR DESCRIPTION
**Pull request by zachwhaley**
Do not add listeners if page is not a PR page.
Use a single event for both Squash and Merge.
Re-add listeners on new comments.

Fixes #11 

Inspiration
- https://github.com/sindresorhus/refined-github/blob/master/source/github-events/on-new-comments.ts
- https://github.com/sindresorhus/refined-github/blob/master/source/github-events/on-pr-merge-panel-open.ts

### CODE REVIEW

**Comment by zachwhaley** [comment]
@GMNGeoffrey I believe this fixes #11 
Would you mind testing?

**Comment by GMNGeoffrey** [comment]
Hmmm well I just tried it out and it seems to work, but it's hard to tell since it was also working intermittently before...

File: content.js [hunk 1]
```diff
@@ -21,18 +21,24 @@ function copyPrDescription() {
   messageField.value = commitBody;
 }
 
-function addMergeListeners() {
-  const squashButton = document.querySelector('.merge-message .btn-group-squash');
-  const mergeButton = document.querySelector('.merge-message .btn-group-merge');
+function addMergeListener(event) {
+  if (!window.location.pathname.match("/pull/[0-9]+$")) return;
```
Comment (GMNGeoffrey) [inline content.js:25]: Maybe this should gate everything? I'm not sure exactly when content.js gets loaded/run, but I'm guessing it is re-invoked when the location changes?

Something like:


```
function main() {
  if (!window.location.pathname.match("/pull/[0-9]+$")) return;

  // Run on extension load.
  addMergeListener();

  // Run on AJAX.
  document.addEventListener('pjax:end', addMergeListener);

  // Run when new comments are added, removed, edited, etc.
  const comments = document.querySelector('.js-discussion');
  if (comments) {
    const observer = new MutationObserver(addMergeListener);
    observer.observe(comments, {childList: true});
  }
}

main();
```

WDYT?

File: content.js [hunk 2]
```diff
@@ -21,18 +21,24 @@ function copyPrDescription() {
...
-  if (squashButton) {
-    squashButton.addEventListener('click', copyPrDescription);
-  }
-  if (mergeButton) {
-    mergeButton.addEventListener('click', copyPrDescription);
-  }
+  const prMergePanel = document.querySelector('.js-merge-pr:not(.is-rebasing)');
+  if (!prMergePanel) return;
 
+  prMergePanel.addEventListener('details:toggled', copyPrDescription);
```
Comment (GMNGeoffrey) [inline content.js:30]: Should we try to avoid adding the same handler multiple times? Looks like Refined GitHub uses memoization for that purpose

File: content.js [hunk 3]
```diff
@@ -21,18 +21,24 @@ function copyPrDescription() {
...
 
-document.addEventListener('pjax:end', addMergeListeners);
-addMergeListeners();
+// Run on extension load.
+addMergeListener();
+
+// Run on AJAX.
+document.addEventListener('pjax:end', addMergeListener);
+
+// Run when new comments are added, removed, edited, etc.
```
Comment (GMNGeoffrey) [inline content.js:39]: Maybe good to explain why? I still don't really understand why adding a comment screws things up :-D

File: content.js (hunk 2 above)
Comment (zachwhaley) [reply content.js:30]: I believe `addEventHandler` handles this.

https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Multiple_identical_event_listeners

File: content.js (hunk 3 above)
Comment (zachwhaley) [reply content.js:39]: Honestly I'm not sure either.  Something about how GitHub refreshes the comments discards all events ¯\_(ツ)_/¯

**Comment by zachwhaley** [comment]
> Hmmm well I just tried it out and it seems to work, but it's hard to tell since it was also working intermittently before...

Well I know it at least fixes the new comments issue 😅 

I can leave the issue up for a bit after merging this for good measure.

File: content.js (hunk 3 above)
Comment (GMNGeoffrey) [reply content.js:39]: Weird... Maybe just that (complete with shruggie) would be good :-D

File: content.js (hunk 1 above)
Comment (GMNGeoffrey) [reply content.js:25]: Testing locally this seems to still work for me

File: content.js (hunk 2 above)
Comment (GMNGeoffrey) [reply content.js:30]: > > Hmmm well I just tried it out and it seems to work, but it's hard to tell since it was also working intermittently before...
> 
> Well I know it at least fixes the new comments issue 
> 
> I can leave the issue up for a bit after merging this for good measure.

Up to you :smile: Can always reopen if it reoccurs.

**Comment by zachwhaley** [comment]
Test
