### PR TITLE
fix: Fix failure to copy description

### LINKED ISSUE #11: Listener frequently added but not triggered
I'm a bit hesitant to open an issue that is basically "it doesn't work", but I'm finding that frequently the description copy isn't happening.

I added a bunch of logging to see what's going wrong, and it looks like the listener gets added but doesn't get triggered. https://github.com/GMNGeoffrey/squashed-merge-message/blob/logging/content.js

"Adding listener" shows up in the logs, but none of the other messages do. This is an intermittent issue. If I empty cache and hard reload a few times, it usually works eventually. I'll continue to try and see if I can get a reliable repro. It seems like once I've gotten it to work for a PR it works every time.

### PR DESCRIPTION
**Pull request by joeyparrish**
Instead of copying the PR title and body from the HTML elements, which
may not exist yet, use the GitHub API to query the necessary metadata.

Closes #11

### CODE REVIEW

**Comment by zachwhaley** [comment]
@joeyparrish Thanks y'all for looking into this, and for the PR!  I'll need to test this with GitHub Enterprise before merging.

**Comment by zachwhaley** [comment]
@joeyparrish sounds good!  Sorry I haven’t had time to test this out. I’ll try to get to it soon :)

**Comment by joeyparrish** [comment]
No worries!  I feel confident, based on the docs, that it won't work yet.  :-)  If you can either grant me temporary read-only access to an enterprise repo so I can experiment, or work out for me how to get the GitHub Enterprise hostname from `window.location`, I think the solution I outlined above will work.

Thanks!

File: content.js [hunk 1]
```diff
@@ -43,10 +34,10 @@ function copyPrDescription() {
     return;
   };
 
-  const commitTitle = `${prTitleEl.value} (#${prNumberMatch.groups['pr_number']})`;
+  const commitTitle = `${prMetadata.title} (#${prNumber})`;
 
   // Remove leading HTML comments
-  let commitBody = prBodyEl.textContent.replace(/^<!--.*?-->\n*/gs, '');
+  let commitBody = prMetadata.body.replace(/^<!--.*?-->\n*/gs, '');
```
Comment (GMNGeoffrey) [inline content.js:40]: `body` can be null here if the PR description is empty. I think that wasn't true of the textContent before. Something like this should fix

```js
const prTitle = prMetadata.title || '';
const prBody = prMetadata.body || '';
```

**Comment by zachwhaley** [comment]
So it is fairly simple to get the URL of the page with `window.location.host` or `window.location.origin`, but with GH enterprise you cannot make API calls without authentication.  Also, I would imagine the API call wouldn't work for private repos in GH either.  So I'm not sure this API solution is going to work in the broader sense 😞 

It would be very nice if we could somehow force GitHub to populate that body for us, but that may be even more fragile than the current implementation.  I'm still thinking about this 🤔

**Comment by joeyparrish** [comment]
Before trying the API route, I tried to automate triggering the edit buttons.  It was difficult, because even the buttons are created lazily.  So there ends up being a sequence of things to press, the elements have no IDs, and the combinations of classes aren't even unique.  😞

The extension already needs configuration for GitHub Enterprises, right?  (Add to this domain or some such thing?)  Could we expand on that to add a PAT for such domains at the same time?

The alternative to auto-button-clicking and authentication tokens seems to be shuttering the project, since it doesn't currently work.  I'm all for making this work everywhere, but I'd rather have a solution for public repos than nothing at all.  And refined-github doesn't seem to be making progress toward an equivalent feature.

**Comment by zachwhaley** [comment]
> Before trying the API route, I tried to automate triggering the edit buttons. It was difficult, because even the buttons are created lazily. So there ends up being a sequence of things to press, the elements have no IDs, and the combinations of classes aren't even unique. 😞

I was able to make this work, albeit I do not know how reliable it is.

> The alternative to auto-button-clicking and authentication tokens seems to be shuttering the project, since it doesn't currently work. I'm all for making this work everywhere, but I'd rather have a solution for public repos than nothing at all. And refined-github doesn't seem to be making progress toward an equivalent feature.

I agree, I think we can start with an attempt to fetch the PR body, if that fails then fallback to trying to find the PR body in the HTML, if it cannot be found then you could use this code to try to force it to appear

```js
async function makePrDescriptionAppear() {
  const detailsButton = document.querySelector('.timeline-comment-actions details:last-child summary[role="button"]');
  detailsButton.click();
  const editButton = await waitForElement('details-menu > button.dropdown-item.btn-link.js-comment-edit-button');
  editButton.click();
  const cancelButton = await waitForElement('button.js-comment-cancel-button.btn-danger.btn');
  cancelButton.click();
}
```

@joeyparrish Are you up for making those changes?

finally,

> The extension already needs configuration for GitHub Enterprises, right? (Add to this domain or some such thing?) Could we expand on that to add a PAT for such domains at the same time?

You are right, and refined-github has some kind of mechanism to use a PAT.  I can look into this after this issue is resolved for public repos.

**Comment by joeyparrish** [comment]
Brilliant!  So this will:

1. Prefer PR body textarea
2. Fall back to API
3. Fall back to triggering buttons if the API fails

The API option is so we don't have to trust the button-triggering to work reliably or be resistant to future changes in the UI, and the button-triggering option will give us functionality for GitHub Enterprise.

Let me know if I got any of that wrong, and I'll make adjustments.

**Comment by joeyparrish** [comment]
Actually, now that I'm working on the code, it seems to me to make more sense to attempt to trigger the buttons first.  I'll have one method to get the metadata from the document, which will include clicking the buttons if needed.  If that fails, it will use the API as a fallback.

If you disagree, I'm happy to make further changes.

File: content.js [hunk 2]
```diff
@@ -49,6 +55,49 @@ async function copyPrDescription() {
...
+  }
+
+  return {
+    title: prTitleEl.value,
+    body: prBodyEl.textContent,
+  };
+}
+
+async function getPrMetadataFromApi(repo, prNumber) {
+  const response = await fetch(`https://api.github.com/repos/${repo}/pulls/${prNumber}`);
```
Comment (zachwhaley) [inline content.js:83]: Should we check for error here? or perhaps only run this if we know the site is github.com, because we know this is not going to work in Enterprise or Private repos.

You can use `window.location.host` to check if the site is `github.com`

File: content.js [hunk 3]
```diff
@@ -49,6 +55,49 @@ async function copyPrDescription() {
...
+  const prMetadata = await response.json();
+  return {
+    // These could be null in some cases, so replace nulls with empty strings.
+    title: prMetadata.title || '',
+    body: prMetadata.body || '',
+  };
+}
+
+async function makePrDescriptionAppear() {
```
Comment (zachwhaley) [inline content.js:92]: A side effect of doing this is that, at least on my computer, it scrolls to the top of the page which is a bit jarring.  I wonder if there's a way to either stop that from happening or to tell the browser to go back to the bottom of the page.

Makes me wonder if it wouldn't be better to start with API approach first, and save this for last since it is the most invasive to the user.  Plus, for public repos, the API approach seems to be very easy and future proof.  What do you think?

File: content.js [hunk 4]
```diff
@@ -58,6 +55,49 @@ function copyPrDescription() {
...
+  const detailsButton = document.querySelector('.timeline-comment-actions details:last-child summary[role="button"]');
+  detailsButton.click();
+  const editButton = await waitForElement('details-menu > button.dropdown-item.btn-link.js-comment-edit-button');
+  editButton.click();
+  const cancelButton = await waitForElement('button.js-comment-cancel-button.btn-danger.btn');
+  cancelButton.click();
```
Comment (zachwhaley) [inline content.js:98]: Add this to bring focus back to the commit message after edit is pressed.

```suggestion
  cancelButton.click();
  const commitText = document.getElementById('merge_message_field');
  commitText.focus();
```

File: content.js [hunk 5]
```diff
@@ -43,10 +40,10 @@ function copyPrDescription() {
     return;
   };
 
-  const commitTitle = `${prTitleEl.value} (#${prNumberMatch.groups['pr_number']})`;
+  const commitTitle = `${prMetadata.title} (#${prNumber})`;
 
   // Remove leading HTML comments
-  let commitBody = prBodyEl.textContent.replace(/^<!--.*?-->\n*/gs, '');
+  let commitBody = prMetadata.body.replace(/^<!--.*?-->\n*/gs, '');
```
Comment (zachwhaley) [inline content.js:46]: The result from the API keeps a newline at the top.  Trim that off with 

```suggestion
  let commitBody = prMetadata.body.replace(/^<!--.*?-->\n*/gs, '').trim();
```

File: content.js [hunk 6]
```diff
@@ -6,28 +6,25 @@ function debug(message) {
...
-  if (!prBodyEl) {
-    prBodyEl = document.querySelector('.comment-form-textarea[name="pull_request[body]"]');
-    if (!prBodyEl) {
-      warn('failed to find PR body element');
-      return;
-    };
-  };
+  let prMetadata = await getPrMetadataFromDocument();
+  if (!prMetadata) {
+    prMetadata = await getPrMetadataFromApi();
```
Comment (zachwhaley) [inline content.js:22]:
```suggestion
    prMetadata = await getPrMetadataFromApi(repo, prNumber);
```

File: content.js (hunk 2 above)
Comment (joeyparrish) [reply content.js:83]: Since we're parsing location.pathname to get the repo and PR number for the parameters, I think a check at that level might be more sensible.  I'll add it there.

File: content.js (hunk 3 above)
Comment (joeyparrish) [reply content.js:92]: Sure, that seems reasonable.

File: content.js (hunk 6 above)
Comment (joeyparrish) [reply content.js]: I noticed this myself and already committed a fix.  (It took me a few hours to get back to testing everything in that second commit.)

File: content.js (hunk 3 above)
Comment (joeyparrish) [reply content.js:100]: Done

File: content.js (hunk 2 above)
Comment (joeyparrish) [reply content.js:91]: Done

**Comment by joeyparrish** [comment]
Okay, this appears to be working now.  Thanks for all your suggestions!

File: content.js [hunk 7]
```diff
@@ -6,28 +6,34 @@ function debug(message) {
...
-    prBodyEl = document.querySelector('.comment-form-textarea[name="pull_request[body]"]');
-    if (!prBodyEl) {
-      warn('failed to find PR body element');
-      return;
-    };
-  };
+  let prMetadata = null;
+
+  // For public repos, prefer the API.
+  if (window.location.host == 'github.com') {
```
Comment (zachwhaley) [inline content.js:23]: Javascript 🤷🏻 

```suggestion
  if (window.location.host === 'github.com') {
```

**Comment by joeyparrish** [comment]
Thanks so much!
